### ISSUE TITLE
Meetings/to-do

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/nmrrr-workflow#3]
2021-04-13
AMP, MEB, KFP

- plug-and-play for binset names
- add more solvents
    - DMSO
    - D2O
    - MeOD
    - 

- Data viz:
    - spectra, including stacked (with region bins labelled and/or colored)
    - bar plots to show the percent of NMR signal (could do a version that is stacked)
    - 

- Statistical techniques:
    - PCA, NMDS, RDA (?), PERMANOVA

- Tutorials and vignettes

@amyerspigg will find binsets: May-15 (see powerpoint Morgan did for lit review of bins used in the literature)
@mbarnes7 will create list of items to include in tutorial and vignettes (the data viz and stats)

---

- stick to only 1H for now, add more nuclei later
- 2D? next level

**Comment by kaizadp** [comment]
June 5

functions and workflow prepared for:
- processing spectra and peaks files from MNova
- plot spectra, with superimposed staggering for samples
- relative abundance calculation
- relative abundance bar plots
- PERMANOVA (needs automating)
- PCA (needs automating)

**Comment by kaizadp** [comment]
June 18 
BBL, KFP

- what is the objective of the package?
- what unique functionality do we want to provide?
- what goes in the package vs. vignette?
    - package:
        - processing
        - spectra
        - relabund calculations
    - vignettes:
        - relabund graphs
        - stats
        - general workflow example
- may need to move away from dplyr for some functions
- need sample data for package testing
- provide sample data in the package for users?

**Comment by kaizadp** [comment]
June 18
AMP, MEB, KFP

- bin formats: make a function to convert to MNova-friendly formats?
- AMP and MEB will add new binsets and datasets and test the code in the "test" branch.

**Comment by bpbond** [comment]
Created an R package repository for this work: https://github.com/bpbond/nmrrr

**Comment by kaizadp** [comment]
July 20
AMP, MEB, KFP

- **new way to export peaks:** export peaks: Save As... script NMR peak table. @kaizadp will check code to import these
- peak peaking vs. line fitting
- peak picking vs. integrating. different methods. but if you don't deconvolute, you could over-interpret.
- mass exporting? @mbarnes7 will look into it

**test data**
- [x] AMP has 4 samples, exported as tab-separated .csv. KFP will test the code.

**functionality**
- [x] add AUC function to mimic MNova integration. 

**wiki:** 
- show what the output files should look like. including corekey
- add disclaimers for processing: we are not teaching you about processing, aka _garbage in, garbage out_
- try example for other nuclei?

**target journals**
- see #4
- PLoSONE, maybe others

**Comment by kaizadp** [comment]
- [ ] **test code on a Windows computer!**

**Comment by bpbond** [comment]
We will set up automated tests and GitHub Actions to do this.

**Comment by kaizadp** [comment]
Ooh, ok! 
I've never done GitHub Actions, so I'm excited about it. 
Also, now I don't have to power up my old POS Windows computer to run tests.

**Comment by bpbond** [comment]
Let's go over this on Thursday?
